version: '3'

services:
  db:
    image: mariadb:10.9.4
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=library
    expose:
      - 3306

  library:
    build: .
    restart: unless-stopped
    network_mode: bridge
    depends_on:
      - db
    ports:
      - "12003:12003"


